// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: packager.proto

package packager

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PackagerService_GeneratePlaylist_FullMethodName = "/packager.PackagerService/GeneratePlaylist"
)

// PackagerServiceClient is the client API for PackagerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PackagerServiceClient interface {
	GeneratePlaylist(ctx context.Context, in *PackagerRequest, opts ...grpc.CallOption) (*PackagerResponse, error)
}

type packagerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPackagerServiceClient(cc grpc.ClientConnInterface) PackagerServiceClient {
	return &packagerServiceClient{cc}
}

func (c *packagerServiceClient) GeneratePlaylist(ctx context.Context, in *PackagerRequest, opts ...grpc.CallOption) (*PackagerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PackagerResponse)
	err := c.cc.Invoke(ctx, PackagerService_GeneratePlaylist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PackagerServiceServer is the server API for PackagerService service.
// All implementations must embed UnimplementedPackagerServiceServer
// for forward compatibility.
type PackagerServiceServer interface {
	GeneratePlaylist(context.Context, *PackagerRequest) (*PackagerResponse, error)
	mustEmbedUnimplementedPackagerServiceServer()
}

// UnimplementedPackagerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPackagerServiceServer struct{}

func (UnimplementedPackagerServiceServer) GeneratePlaylist(context.Context, *PackagerRequest) (*PackagerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GeneratePlaylist not implemented")
}
func (UnimplementedPackagerServiceServer) mustEmbedUnimplementedPackagerServiceServer() {}
func (UnimplementedPackagerServiceServer) testEmbeddedByValue()                         {}

// UnsafePackagerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PackagerServiceServer will
// result in compilation errors.
type UnsafePackagerServiceServer interface {
	mustEmbedUnimplementedPackagerServiceServer()
}

func RegisterPackagerServiceServer(s grpc.ServiceRegistrar, srv PackagerServiceServer) {
	// If the following call pancis, it indicates UnimplementedPackagerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PackagerService_ServiceDesc, srv)
}

func _PackagerService_GeneratePlaylist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PackagerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PackagerServiceServer).GeneratePlaylist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PackagerService_GeneratePlaylist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PackagerServiceServer).GeneratePlaylist(ctx, req.(*PackagerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PackagerService_ServiceDesc is the grpc.ServiceDesc for PackagerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PackagerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "packager.PackagerService",
	HandlerType: (*PackagerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GeneratePlaylist",
			Handler:    _PackagerService_GeneratePlaylist_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "packager.proto",
}
