// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.3
// 	protoc        v5.29.3
// source: autoscaler.proto

package autoscaler

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Scaling action
type ScalingAction int32

const (
	ScalingAction_SCALE_UP   ScalingAction = 0
	ScalingAction_SCALE_DOWN ScalingAction = 1
	ScalingAction_NO_ACTION  ScalingAction = 2
)

// Enum value maps for ScalingAction.
var (
	ScalingAction_name = map[int32]string{
		0: "SCALE_UP",
		1: "SCALE_DOWN",
		2: "NO_ACTION",
	}
	ScalingAction_value = map[string]int32{
		"SCALE_UP":   0,
		"SCALE_DOWN": 1,
		"NO_ACTION":  2,
	}
)

func (x ScalingAction) Enum() *ScalingAction {
	p := new(ScalingAction)
	*p = x
	return p
}

func (x ScalingAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ScalingAction) Descriptor() protoreflect.EnumDescriptor {
	return file_autoscaler_proto_enumTypes[0].Descriptor()
}

func (ScalingAction) Type() protoreflect.EnumType {
	return &file_autoscaler_proto_enumTypes[0]
}

func (x ScalingAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ScalingAction.Descriptor instead.
func (ScalingAction) EnumDescriptor() ([]byte, []int) {
	return file_autoscaler_proto_rawDescGZIP(), []int{0}
}

// Scaling target
type ScalingTarget int32

const (
	ScalingTarget_TRANSCODER   ScalingTarget = 0
	ScalingTarget_PACKAGER     ScalingTarget = 1
	ScalingTarget_STORAGE      ScalingTarget = 2
	ScalingTarget_PROBE        ScalingTarget = 3
	ScalingTarget_INGRESS      ScalingTarget = 4
	ScalingTarget_ORCHESTRATOR ScalingTarget = 5
	ScalingTarget_DRM          ScalingTarget = 6
)

// Enum value maps for ScalingTarget.
var (
	ScalingTarget_name = map[int32]string{
		0: "TRANSCODER",
		1: "PACKAGER",
		2: "STORAGE",
		3: "PROBE",
		4: "INGRESS",
		5: "ORCHESTRATOR",
		6: "DRM",
	}
	ScalingTarget_value = map[string]int32{
		"TRANSCODER":   0,
		"PACKAGER":     1,
		"STORAGE":      2,
		"PROBE":        3,
		"INGRESS":      4,
		"ORCHESTRATOR": 5,
		"DRM":          6,
	}
)

func (x ScalingTarget) Enum() *ScalingTarget {
	p := new(ScalingTarget)
	*p = x
	return p
}

func (x ScalingTarget) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ScalingTarget) Descriptor() protoreflect.EnumDescriptor {
	return file_autoscaler_proto_enumTypes[1].Descriptor()
}

func (ScalingTarget) Type() protoreflect.EnumType {
	return &file_autoscaler_proto_enumTypes[1]
}

func (x ScalingTarget) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ScalingTarget.Descriptor instead.
func (ScalingTarget) EnumDescriptor() ([]byte, []int) {
	return file_autoscaler_proto_rawDescGZIP(), []int{1}
}

// Metric Name
type MetricName int32

const (
	MetricName_CPU_UTILIZATION        MetricName = 0
	MetricName_MEMORY_UTILIZATION     MetricName = 1
	MetricName_QUEUE_LENGTH           MetricName = 2
	MetricName_JOB_PROCESSING_LATENCY MetricName = 3
	MetricName_ERROR_RATE             MetricName = 4
)

// Enum value maps for MetricName.
var (
	MetricName_name = map[int32]string{
		0: "CPU_UTILIZATION",
		1: "MEMORY_UTILIZATION",
		2: "QUEUE_LENGTH",
		3: "JOB_PROCESSING_LATENCY",
		4: "ERROR_RATE",
	}
	MetricName_value = map[string]int32{
		"CPU_UTILIZATION":        0,
		"MEMORY_UTILIZATION":     1,
		"QUEUE_LENGTH":           2,
		"JOB_PROCESSING_LATENCY": 3,
		"ERROR_RATE":             4,
	}
)

func (x MetricName) Enum() *MetricName {
	p := new(MetricName)
	*p = x
	return p
}

func (x MetricName) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MetricName) Descriptor() protoreflect.EnumDescriptor {
	return file_autoscaler_proto_enumTypes[2].Descriptor()
}

func (MetricName) Type() protoreflect.EnumType {
	return &file_autoscaler_proto_enumTypes[2]
}

func (x MetricName) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MetricName.Descriptor instead.
func (MetricName) EnumDescriptor() ([]byte, []int) {
	return file_autoscaler_proto_rawDescGZIP(), []int{2}
}

// Scaling policy
type ScalingPolicy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MetricName    MetricName             `protobuf:"varint,1,opt,name=metric_name,json=metricName,proto3,enum=autoscaler.MetricName" json:"metric_name,omitempty"`
	Threshold     float64                `protobuf:"fixed64,2,opt,name=threshold,proto3" json:"threshold,omitempty"`
	Action        ScalingAction          `protobuf:"varint,3,opt,name=action,proto3,enum=autoscaler.ScalingAction" json:"action,omitempty"`
	Target        ScalingTarget          `protobuf:"varint,4,opt,name=target,proto3,enum=autoscaler.ScalingTarget" json:"target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScalingPolicy) Reset() {
	*x = ScalingPolicy{}
	mi := &file_autoscaler_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScalingPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScalingPolicy) ProtoMessage() {}

func (x *ScalingPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_autoscaler_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScalingPolicy.ProtoReflect.Descriptor instead.
func (*ScalingPolicy) Descriptor() ([]byte, []int) {
	return file_autoscaler_proto_rawDescGZIP(), []int{0}
}

func (x *ScalingPolicy) GetMetricName() MetricName {
	if x != nil {
		return x.MetricName
	}
	return MetricName_CPU_UTILIZATION
}

func (x *ScalingPolicy) GetThreshold() float64 {
	if x != nil {
		return x.Threshold
	}
	return 0
}

func (x *ScalingPolicy) GetAction() ScalingAction {
	if x != nil {
		return x.Action
	}
	return ScalingAction_SCALE_UP
}

func (x *ScalingPolicy) GetTarget() ScalingTarget {
	if x != nil {
		return x.Target
	}
	return ScalingTarget_TRANSCODER
}

// Scaling request
type ScalingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrgId         *OrganizationId        `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	Policies      []*ScalingPolicy       `protobuf:"bytes,2,rep,name=policies,proto3" json:"policies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScalingRequest) Reset() {
	*x = ScalingRequest{}
	mi := &file_autoscaler_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScalingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScalingRequest) ProtoMessage() {}

func (x *ScalingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_autoscaler_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScalingRequest.ProtoReflect.Descriptor instead.
func (*ScalingRequest) Descriptor() ([]byte, []int) {
	return file_autoscaler_proto_rawDescGZIP(), []int{1}
}

func (x *ScalingRequest) GetOrgId() *OrganizationId {
	if x != nil {
		return x.OrgId
	}
	return nil
}

func (x *ScalingRequest) GetPolicies() []*ScalingPolicy {
	if x != nil {
		return x.Policies
	}
	return nil
}

// Scaling response
type ScalingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScalingResponse) Reset() {
	*x = ScalingResponse{}
	mi := &file_autoscaler_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScalingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScalingResponse) ProtoMessage() {}

func (x *ScalingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_autoscaler_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScalingResponse.ProtoReflect.Descriptor instead.
func (*ScalingResponse) Descriptor() ([]byte, []int) {
	return file_autoscaler_proto_rawDescGZIP(), []int{2}
}

func (x *ScalingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Organization ID
type OrganizationId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrgId         string                 `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrganizationId) Reset() {
	*x = OrganizationId{}
	mi := &file_autoscaler_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrganizationId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrganizationId) ProtoMessage() {}

func (x *OrganizationId) ProtoReflect() protoreflect.Message {
	mi := &file_autoscaler_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrganizationId.ProtoReflect.Descriptor instead.
func (*OrganizationId) Descriptor() ([]byte, []int) {
	return file_autoscaler_proto_rawDescGZIP(), []int{3}
}

func (x *OrganizationId) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_autoscaler_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_autoscaler_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_autoscaler_proto_rawDescGZIP(), []int{4}
}

var File_autoscaler_proto protoreflect.FileDescriptor

var file_autoscaler_proto_rawDesc = []byte{
	0x0a, 0x10, 0x61, 0x75, 0x74, 0x6f, 0x73, 0x63, 0x61, 0x6c, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0a, 0x61, 0x75, 0x74, 0x6f, 0x73, 0x63, 0x61, 0x6c, 0x65, 0x72, 0x22, 0xcc,
	0x01, 0x0a, 0x0d, 0x53, 0x63, 0x61, 0x6c, 0x69, 0x6e, 0x67, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79,
	0x12, 0x37, 0x0a, 0x0b, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x61, 0x75, 0x74, 0x6f, 0x73, 0x63, 0x61, 0x6c,
	0x65, 0x72, 0x2e, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x0a, 0x6d,
	0x65, 0x74, 0x72, 0x69, 0x63, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x68, 0x72,
	0x65, 0x73, 0x68, 0x6f, 0x6c, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x09, 0x74, 0x68,
	0x72, 0x65, 0x73, 0x68, 0x6f, 0x6c, 0x64, 0x12, 0x31, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x19, 0x2e, 0x61, 0x75, 0x74, 0x6f, 0x73, 0x63,
	0x61, 0x6c, 0x65, 0x72, 0x2e, 0x53, 0x63, 0x61, 0x6c, 0x69, 0x6e, 0x67, 0x41, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x31, 0x0a, 0x06, 0x74, 0x61,
	0x72, 0x67, 0x65, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x19, 0x2e, 0x61, 0x75, 0x74,
	0x6f, 0x73, 0x63, 0x61, 0x6c, 0x65, 0x72, 0x2e, 0x53, 0x63, 0x61, 0x6c, 0x69, 0x6e, 0x67, 0x54,
	0x61, 0x72, 0x67, 0x65, 0x74, 0x52, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x22, 0x7a, 0x0a,
	0x0e, 0x53, 0x63, 0x61, 0x6c, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x31, 0x0a, 0x06, 0x6f, 0x72, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x61, 0x75, 0x74, 0x6f, 0x73, 0x63, 0x61, 0x6c, 0x65, 0x72, 0x2e, 0x4f, 0x72, 0x67,
	0x61, 0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x52, 0x05, 0x6f, 0x72, 0x67,
	0x49, 0x64, 0x12, 0x35, 0x0a, 0x08, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x65, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x61, 0x75, 0x74, 0x6f, 0x73, 0x63, 0x61, 0x6c, 0x65,
	0x72, 0x2e, 0x53, 0x63, 0x61, 0x6c, 0x69, 0x6e, 0x67, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x52,
	0x08, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x65, 0x73, 0x22, 0x2b, 0x0a, 0x0f, 0x53, 0x63, 0x61,
	0x6c, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x27, 0x0a, 0x0e, 0x4f, 0x72, 0x67, 0x61, 0x6e, 0x69,
	0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x15, 0x0a, 0x06, 0x6f, 0x72, 0x67, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6f, 0x72, 0x67, 0x49, 0x64, 0x22,
	0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x2a, 0x3c, 0x0a, 0x0d, 0x53, 0x63, 0x61, 0x6c,
	0x69, 0x6e, 0x67, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0c, 0x0a, 0x08, 0x53, 0x43, 0x41,
	0x4c, 0x45, 0x5f, 0x55, 0x50, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x53, 0x43, 0x41, 0x4c, 0x45,
	0x5f, 0x44, 0x4f, 0x57, 0x4e, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x4e, 0x4f, 0x5f, 0x41, 0x43,
	0x54, 0x49, 0x4f, 0x4e, 0x10, 0x02, 0x2a, 0x6d, 0x0a, 0x0d, 0x53, 0x63, 0x61, 0x6c, 0x69, 0x6e,
	0x67, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x12, 0x0e, 0x0a, 0x0a, 0x54, 0x52, 0x41, 0x4e, 0x53,
	0x43, 0x4f, 0x44, 0x45, 0x52, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x50, 0x41, 0x43, 0x4b, 0x41,
	0x47, 0x45, 0x52, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x54, 0x4f, 0x52, 0x41, 0x47, 0x45,
	0x10, 0x02, 0x12, 0x09, 0x0a, 0x05, 0x50, 0x52, 0x4f, 0x42, 0x45, 0x10, 0x03, 0x12, 0x0b, 0x0a,
	0x07, 0x49, 0x4e, 0x47, 0x52, 0x45, 0x53, 0x53, 0x10, 0x04, 0x12, 0x10, 0x0a, 0x0c, 0x4f, 0x52,
	0x43, 0x48, 0x45, 0x53, 0x54, 0x52, 0x41, 0x54, 0x4f, 0x52, 0x10, 0x05, 0x12, 0x07, 0x0a, 0x03,
	0x44, 0x52, 0x4d, 0x10, 0x06, 0x2a, 0x77, 0x0a, 0x0a, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x13, 0x0a, 0x0f, 0x43, 0x50, 0x55, 0x5f, 0x55, 0x54, 0x49, 0x4c, 0x49,
	0x5a, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x10, 0x00, 0x12, 0x16, 0x0a, 0x12, 0x4d, 0x45, 0x4d, 0x4f,
	0x52, 0x59, 0x5f, 0x55, 0x54, 0x49, 0x4c, 0x49, 0x5a, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x10, 0x01,
	0x12, 0x10, 0x0a, 0x0c, 0x51, 0x55, 0x45, 0x55, 0x45, 0x5f, 0x4c, 0x45, 0x4e, 0x47, 0x54, 0x48,
	0x10, 0x02, 0x12, 0x1a, 0x0a, 0x16, 0x4a, 0x4f, 0x42, 0x5f, 0x50, 0x52, 0x4f, 0x43, 0x45, 0x53,
	0x53, 0x49, 0x4e, 0x47, 0x5f, 0x4c, 0x41, 0x54, 0x45, 0x4e, 0x43, 0x59, 0x10, 0x03, 0x12, 0x0e,
	0x0a, 0x0a, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x5f, 0x52, 0x41, 0x54, 0x45, 0x10, 0x04, 0x32, 0x9f,
	0x01, 0x0a, 0x11, 0x41, 0x75, 0x74, 0x6f, 0x73, 0x63, 0x61, 0x6c, 0x65, 0x72, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x41, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x53, 0x63, 0x61, 0x6c, 0x69,
	0x6e, 0x67, 0x52, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x12, 0x11, 0x2e, 0x61, 0x75, 0x74, 0x6f, 0x73, 0x63, 0x61, 0x6c, 0x65, 0x72, 0x2e, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x1a, 0x11, 0x2e, 0x61, 0x75, 0x74, 0x6f, 0x73, 0x63, 0x61, 0x6c, 0x65,
	0x72, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x47, 0x0a, 0x0c, 0x41, 0x70, 0x70, 0x6c, 0x79,
	0x53, 0x63, 0x61, 0x6c, 0x69, 0x6e, 0x67, 0x12, 0x1a, 0x2e, 0x61, 0x75, 0x74, 0x6f, 0x73, 0x63,
	0x61, 0x6c, 0x65, 0x72, 0x2e, 0x53, 0x63, 0x61, 0x6c, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x61, 0x75, 0x74, 0x6f, 0x73, 0x63, 0x61, 0x6c, 0x65, 0x72,
	0x2e, 0x53, 0x63, 0x61, 0x6c, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x42, 0x33, 0x5a, 0x31, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d,
	0x65, 0x64, 0x69, 0x61, 0x70, 0x72, 0x6f, 0x64, 0x63, 0x61, 0x73, 0x74, 0x2f, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x75, 0x74, 0x6f, 0x73,
	0x63, 0x61, 0x6c, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_autoscaler_proto_rawDescOnce sync.Once
	file_autoscaler_proto_rawDescData = file_autoscaler_proto_rawDesc
)

func file_autoscaler_proto_rawDescGZIP() []byte {
	file_autoscaler_proto_rawDescOnce.Do(func() {
		file_autoscaler_proto_rawDescData = protoimpl.X.CompressGZIP(file_autoscaler_proto_rawDescData)
	})
	return file_autoscaler_proto_rawDescData
}

var file_autoscaler_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_autoscaler_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_autoscaler_proto_goTypes = []any{
	(ScalingAction)(0),      // 0: autoscaler.ScalingAction
	(ScalingTarget)(0),      // 1: autoscaler.ScalingTarget
	(MetricName)(0),         // 2: autoscaler.MetricName
	(*ScalingPolicy)(nil),   // 3: autoscaler.ScalingPolicy
	(*ScalingRequest)(nil),  // 4: autoscaler.ScalingRequest
	(*ScalingResponse)(nil), // 5: autoscaler.ScalingResponse
	(*OrganizationId)(nil),  // 6: autoscaler.OrganizationId
	(*Empty)(nil),           // 7: autoscaler.Empty
}
var file_autoscaler_proto_depIdxs = []int32{
	2, // 0: autoscaler.ScalingPolicy.metric_name:type_name -> autoscaler.MetricName
	0, // 1: autoscaler.ScalingPolicy.action:type_name -> autoscaler.ScalingAction
	1, // 2: autoscaler.ScalingPolicy.target:type_name -> autoscaler.ScalingTarget
	6, // 3: autoscaler.ScalingRequest.org_id:type_name -> autoscaler.OrganizationId
	3, // 4: autoscaler.ScalingRequest.policies:type_name -> autoscaler.ScalingPolicy
	7, // 5: autoscaler.AutoscalerService.GetScalingRecommendations:input_type -> autoscaler.Empty
	4, // 6: autoscaler.AutoscalerService.ApplyScaling:input_type -> autoscaler.ScalingRequest
	7, // 7: autoscaler.AutoscalerService.GetScalingRecommendations:output_type -> autoscaler.Empty
	5, // 8: autoscaler.AutoscalerService.ApplyScaling:output_type -> autoscaler.ScalingResponse
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_autoscaler_proto_init() }
func file_autoscaler_proto_init() {
	if File_autoscaler_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_autoscaler_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_autoscaler_proto_goTypes,
		DependencyIndexes: file_autoscaler_proto_depIdxs,
		EnumInfos:         file_autoscaler_proto_enumTypes,
		MessageInfos:      file_autoscaler_proto_msgTypes,
	}.Build()
	File_autoscaler_proto = out.File
	file_autoscaler_proto_rawDesc = nil
	file_autoscaler_proto_goTypes = nil
	file_autoscaler_proto_depIdxs = nil
}
